//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/AElena.ServiceWrapper.SampleService")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PurchasesLastYearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PurchasesLastYear {
            get {
                return this.PurchasesLastYearField;
            }
            set {
                if ((this.PurchasesLastYearField.Equals(value) != true)) {
                    this.PurchasesLastYearField = value;
                    this.RaisePropertyChanged("PurchasesLastYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="aelena.com/services/sampleservice", ConfigurationName="SampleServiceAsSvcRef2.ISampleService")]
    public interface ISampleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="aelena.com/services/sampleservice/ISampleService/UpdateStatus", ReplyAction="aelena.com/services/sampleservice/ISampleService/UpdateStatusResponse")]
        ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.UpdateStatusResponse UpdateStatus(ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.UpdateStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="aelena.com/services/sampleservice/ISampleService/UpdateStatus", ReplyAction="aelena.com/services/sampleservice/ISampleService/UpdateStatusResponse")]
        System.Threading.Tasks.Task<ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.UpdateStatusResponse> UpdateStatusAsync(ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.UpdateStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="aelena.com/services/sampleservice/ISampleService/GetClient", ReplyAction="aelena.com/services/sampleservice/ISampleService/GetClientResponse")]
        ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.GetClientResponse GetClient(ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.GetClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="aelena.com/services/sampleservice/ISampleService/GetClient", ReplyAction="aelena.com/services/sampleservice/ISampleService/GetClientResponse")]
        System.Threading.Tasks.Task<ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.GetClientResponse> GetClientAsync(ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.GetClientRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateStatus", WrapperNamespace="aelena.com/services/sampleservice", IsWrapped=true)]
    public partial class UpdateStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="aelena.com/services/sampleservice", Order=0)]
        public string myID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="aelena.com/services/sampleservice", Order=1)]
        public int myStatus;
        
        public UpdateStatusRequest() {
        }
        
        public UpdateStatusRequest(string myID, int myStatus) {
            this.myID = myID;
            this.myStatus = myStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateStatusResponse", WrapperNamespace="aelena.com/services/sampleservice", IsWrapped=true)]
    public partial class UpdateStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="aelena.com/services/sampleservice", Order=0)]
        public string UpdateStatusResult;
        
        public UpdateStatusResponse() {
        }
        
        public UpdateStatusResponse(string UpdateStatusResult) {
            this.UpdateStatusResult = UpdateStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClient", WrapperNamespace="aelena.com/services/sampleservice", IsWrapped=true)]
    public partial class GetClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="aelena.com/services/sampleservice", Order=0)]
        public int id;
        
        public GetClientRequest() {
        }
        
        public GetClientRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientResponse", WrapperNamespace="aelena.com/services/sampleservice", IsWrapped=true)]
    public partial class GetClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="aelena.com/services/sampleservice", Order=0)]
        public ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.Client GetClientResult;
        
        public GetClientResponse() {
        }
        
        public GetClientResponse(ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.Client GetClientResult) {
            this.GetClientResult = GetClientResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISampleServiceChannel : ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.ISampleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SampleServiceClient : System.ServiceModel.ClientBase<ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.ISampleService>, ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.ISampleService {
        
        public SampleServiceClient() {
        }
        
        public SampleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SampleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.UpdateStatusResponse UpdateStatus(ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.UpdateStatusRequest request) {
            return base.Channel.UpdateStatus(request);
        }
        
        public System.Threading.Tasks.Task<ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.UpdateStatusResponse> UpdateStatusAsync(ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.UpdateStatusRequest request) {
            return base.Channel.UpdateStatusAsync(request);
        }
        
        public ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.GetClientResponse GetClient(ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.GetClientRequest request) {
            return base.Channel.GetClient(request);
        }
        
        public System.Threading.Tasks.Task<ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.GetClientResponse> GetClientAsync(ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef2.GetClientRequest request) {
            return base.Channel.GetClientAsync(request);
        }
    }
}
