//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/AElena.ServiceWrapper.SampleService")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PurchasesLastYearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PurchasesLastYear {
            get {
                return this.PurchasesLastYearField;
            }
            set {
                if ((this.PurchasesLastYearField.Equals(value) != true)) {
                    this.PurchasesLastYearField = value;
                    this.RaisePropertyChanged("PurchasesLastYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="aelena.com/services/sampleservice", ConfigurationName="SampleServiceAsSvcRef1.ISampleService")]
    public interface ISampleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="aelena.com/services/sampleservice/ISampleService/UpdateStatus", ReplyAction="aelena.com/services/sampleservice/ISampleService/UpdateStatusResponse")]
        string UpdateStatus(string myID, int myStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="aelena.com/services/sampleservice/ISampleService/UpdateStatus", ReplyAction="aelena.com/services/sampleservice/ISampleService/UpdateStatusResponse")]
        System.Threading.Tasks.Task<string> UpdateStatusAsync(string myID, int myStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="aelena.com/services/sampleservice/ISampleService/GetClient", ReplyAction="aelena.com/services/sampleservice/ISampleService/GetClientResponse")]
        ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef1.Client GetClient(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="aelena.com/services/sampleservice/ISampleService/GetClient", ReplyAction="aelena.com/services/sampleservice/ISampleService/GetClientResponse")]
        System.Threading.Tasks.Task<ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef1.Client> GetClientAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISampleServiceChannel : ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef1.ISampleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SampleServiceClient : System.ServiceModel.ClientBase<ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef1.ISampleService>, ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef1.ISampleService {
        
        public SampleServiceClient() {
        }
        
        public SampleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SampleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string UpdateStatus(string myID, int myStatus) {
            return base.Channel.UpdateStatus(myID, myStatus);
        }
        
        public System.Threading.Tasks.Task<string> UpdateStatusAsync(string myID, int myStatus) {
            return base.Channel.UpdateStatusAsync(myID, myStatus);
        }
        
        public ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef1.Client GetClient(int id) {
            return base.Channel.GetClient(id);
        }
        
        public System.Threading.Tasks.Task<ServiceWrapper.Nuget.TestConsole.SampleServiceAsSvcRef1.Client> GetClientAsync(int id) {
            return base.Channel.GetClientAsync(id);
        }
    }
}
